declare module 'react-dev-utils/*'
declare module 'webpack-merge'
declare module 'chalk'
declare module 'fs-extra'
declare module 'std-env'
declare module 'gray-matter'
declare module 'clean-webpack-plugin'
declare module 'assets-webpack-plugin'
