"use strict";
exports.__esModule = true;
var build_1 = require("./commands/build");
exports.build = build_1.build;
var dev_1 = require("./commands/dev");
exports.dev = dev_1.dev;
var dll_1 = require("./commands/dll");
exports.dll = dll_1.dll;
var scss_1 = require("./commands/scss");
exports.scss = scss_1.scss;
